stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim/train_processed.csv
    - src/model/model_building.py
    params:
    - model_building.C
    - model_building.max_iter
    - model_building.solver
    - model_building.max_features
    - model_building.ngram_range
    - data_ingestion.random_state
    outs:
    - bow_vectorizer.pkl
    - logistic_regression.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - bow_vectorizer.pkl
    - logistic_regression.pkl
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - src/model/model_evaluation.py
    outs:
    - experiment_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - experiment_info.json
    - src/model/register_model.py